defaults:
  - _self_
  - preprocessing_pipeline: chunk_classification

dataset_root_dir: "${hydra:runtime.cwd}/../dataset"
audio_dir: "${dataset_root_dir}/audios"
annotations_file: "${dataset_root_dir}/labels.csv"
out_dir: "${dataset_root_dir}/preprocessed_data"
# Random seed for all the libraries
seed: 2727

hydra:
  run:
    dir: ../preprocessing_runs/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True
