defaults:
  - _self_
  - data_module: marine_sound
  - model: recurrent_cnn
  - trainer: base_gpu
  - logger: wandb
  - callbacks: default

experiment_name: "DatathonMarine2022"
labels:
  - "silence"
  - "whistle"
  - "click"
  - "cetaceans_allfreq"
  - "allfreq"
# Random seed for all the libraries
seed: 2727

hydra:
  run:
    dir: ../experiments_runs/${now:%Y-%m-%d_%H-%M-%S}

