_target_: lib.data.preprocessing.ChunkPreprocPipeline
audio_dir: "${audio_dir}"
annotations_file: "${annotations_file}"
out_dir: "${out_dir}"
frame_size: 1024
hop_size: 512
sample_rate: 50000
chunk_size: 256
spec_type: "mel"
only_events: true

