_target_: lib.data.loaders.MarineSoundDataModule
annotations_file: "${hydra:runtime.cwd}/../dataset/preprocessed_data/frame-0.04_hop-0.02_frames-256_spec-mel/labels.tsv"
audio_dir: "${hydra:runtime.cwd}/../dataset/preprocessed_data/frame-0.04_hop-0.02_frames-256_spec-mel/audio_tensors"
labels: ${labels}
batch_size: 64
num_workers: 16
