_target_: lib.data.loaders.MarineSoundDataModule
annotations_file: "${hydra:runtime.cwd}/../dataset/preprocessed_data/frame-0.04_hop-0.02/labels.tsv"
audio_dir: "${hydra:runtime.cwd}/../dataset/preprocessed_data/frame-0.04_hop-0.02/audio_tensors"
labels: ${labels}
batch_size: 32
num_workers: 8
